### Site Settings ###
title               : Prashant Singh
description         : >-                               # >- means to ignore newlines until "url:"
                      I make games and stuff.

url                 : "prashant-singh.github.io"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : prashant-singh/prashant-singh.github.io    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : prashant-singh/prashant-singh.github.io    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Prashant Singh
  job-title         : Game Developer
  city              : Ahmedabad
  State             : Gujarat
  Country           : India
  Country-Code      : IN
  website-url       : https://thisisprashant.com
  image             : assets/profileimg.png
  email             : prashant19194@gmail.com
  facebook          : prashantsingh.xyz
  github            : prashant-singh
  linkedin          : kshatriyaprashant
  twitter           : _prashantsingh_
  phone             : +91 7802898394

#### Pagination ###
#paginate: 6
#paginate_path: "/articles/page-:num/"
#
#
#### Posts Permalink ###
#permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
